version: "3.5"
services:
  centos6samhain:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS6
  centos7samhain:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
  centos8samhain:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS8

volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
  rpm8:
    name: rpm8
