ARG centos=7.9.2009
FROM aursu/rpmbuild:${centos}-build

USER root
RUN yum -y install \
        gnutls-devel \
        libacl-devel \
        libattr-devel \
        "libprelude-devel >= 5.0.0" \
        pcre-devel \
    && yum clean all && rm -rf /var/cache/yum