ARG centos=6.10
FROM aursu/rpmbuild:${centos}-build

USER root
RUN yum -y install \
        gnutls-devel \
        libacl-devel \
        libattr-devel \
        pcre-devel \
    && yum clean all && rm -rf /var/cache/yum